# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('place', models.IntegerField()),
            ],
            options={
                'db_table': 'formula_stats_allpodiums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=30, unique=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('laps', models.IntegerField(default=0)),
                ('time', models.DurationField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_stats.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('color_code', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('laps_number', models.IntegerField()),
                ('lap_record', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_stats.Team'),
        ),
        migrations.AddField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_stats.Track'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=set([('track', 'driver', 'time'), ('track', 'driver')]),
        ),
    ]
